### ISSUE TITLE
Request Headers in Firefox

### ISSUE THREAD

**Issue by LtSalt** [devio/de-x#1]
Just checked, "authorization" and "xcrsf-token" are lowercase in Firefox. Does this make a difference?

**Comment by fbanning** [comment]
I just manually copied them over from the list and adjusted them to match the capitalisation mentioned in the readme file. Script currently running and everything seems to be fine.

**Comment by devio** [comment]
I think it's up to the server-part to accept the lower-case headers, sent by the client. You may just give it a try, and change capitalisation if it doen't work.
